version: "3.9"

services:
  app:
    build:
      context: ./backend/flask-app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend/flask-app/app/app/dist/static:/app/dist/static
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=pass
      - SECRET_KEY=SECRET
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MODEL_API_KEY=${MODEL_API_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - PASSWORD_VALIDITY_MINUTES=${PASSWORD_VALIDITY_MINUTES}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  proxy:
    build:
      context: ./backend/flask-app/proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the entire /etc/letsencrypt directory from the host
      # This is crucial so Nginx can find the certificates in /etc/letsencrypt/live/
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Volume for Certbot webroot challenge (still needed for renewals)
      - ./nginx/certbot/www:/var/www/certbot

volumes:
  mongo-data:
