
services:
  app:
    build:
      context: ./backend/flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/flask-app/app/app:/app
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MODEL_API_KEY=${MODEL_API_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - PASSWORD_VALIDITY_MINUTES=${PASSWORD_VALIDITY_MINUTES}
      - WEB_SERVER_URL=${WEB_SERVER_URL}
    command: >
      sh -c "flask --app . run --debug --host=0.0.0.0"

  mongodb:
    image: mongo:6.0
    volumes:
      - dev-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

volumes:
  dev-data:
