
services:
  app:
    build:
      context: ./backend/flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend/flask-app/app/app:/app
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=pass
      - SECRET_KEY=SECRET
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: >
      sh -c "flask --app . run --debug --host=0.0.0.0"

  mongodb:
    image: mongo:6.0
    volumes:
      - dev-data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"

volumes:
  dev-data:
